### ISSUE TITLE
Milestone 3 Task Trackers

### ISSUE THREAD

**Issue by huijuechen** [UBC-MDS/mini_tidy_python#24]
- [x] Check the branch coverage of test suite for each function, [all 100%](https://github.com/UBC-MDS/mini_tidy_python/blob/master/doc/branch_coverage_result.png).

- [x] Revisit test cases and add additional tests to make sure branch coverage result as expected:
    - [`my_dropna`](https://github.com/UBC-MDS/mini_tidy_python/pull/25/files#diff-8bcc219bf50526c2156f9df169e21b1b)
    -  [`my_gather`](https://github.com/UBC-MDS/mini_tidy_python/pull/23/files#diff-60a9240fd76b9abbde12584f4c4f9aba)
    -  [`my_spread`](https://github.com/UBC-MDS/mini_tidy_python/pull/23/files#diff-8159d4213d2de1ba1382a2fb35ab04a6)

- [x] Add a [licence](https://github.com/UBC-MDS/mini_tidy_python/blob/master/LICENSE)

- [x] Add toy data with the output for [example usage](https://github.com/UBC-MDS/mini_tidy_python/blob/master/doc/ToyDataExampleUsage.ipynb)

- [x] Add control flow diagrams for [three functions](https://github.com/UBC-MDS/mini_tidy_python/blob/master/doc)

**Comment by huijuechen** [comment]
Mar 2

- Below were all completed by Iris and I with links to the files/pull requests added.

**Comment by lyiris22** [comment]
March 3
- Added flow diagrams for `my_gather` and `my_spread`: [#28](https://github.com/UBC-MDS/mini_tidy_python/pull/28)
- Minor modification for the flow on README: [#29](https://github.com/UBC-MDS/mini_tidy_python/pull/29)
